/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.tautua.markdownpapers.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int TAB = 2;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int CHAR_ENTITY_REF = 4;
  /** RegularExpression Id. */
  int NUMERIC_CHAR_REF = 5;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 6;
  /** RegularExpression Id. */
  int CHAR_SEQUENCE = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int AMPERSAND = 9;
  /** RegularExpression Id. */
  int BACKSLASH = 10;
  /** RegularExpression Id. */
  int BACKTICK = 11;
  /** RegularExpression Id. */
  int BANG = 12;
  /** RegularExpression Id. */
  int COMMENT_OPEN = 13;
  /** RegularExpression Id. */
  int COMMENT_CLOSE = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 16;
  /** RegularExpression Id. */
  int DOT = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int GT = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int RBRACKET = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int SHARP = 27;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 28;
  /** RegularExpression Id. */
  int SLASH = 29;
  /** RegularExpression Id. */
  int STAR = 30;
  /** RegularExpression Id. */
  int UNDERSCORE = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "<CHAR_ENTITY_REF>",
    "<NUMERIC_CHAR_REF>",
    "<ESCAPED_CHAR>",
    "<CHAR_SEQUENCE>",
    "<DIGITS>",
    "\"&\"",
    "\"\\\\\"",
    "\"`\"",
    "\"!\"",
    "\"<!--\"",
    "\"-->\"",
    "\":\"",
    "\"\\\"\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"(\"",
    "\"<\"",
    "\"-\"",
    "\"+\"",
    "\"]\"",
    "\")\"",
    "\"#\"",
    "\"\\\'\"",
    "\"/\"",
    "\"*\"",
    "\"_\"",
  };

}
