/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.tautua.markdownpapers.ast;

import org.tautua.markdownpapers.parser.*;

public interface ParserTreeConstants
{
  public int JJTDOCUMENT = 0;
  public int JJTVOID = 1;
  public int JJTHEADER = 2;
  public int JJTRULER = 3;
  public int JJTQUOTE = 4;
  public int JJTLINE = 5;
  public int JJTCODE = 6;
  public int JJTCODETEXT = 7;
  public int JJTRESOURCEDEFINITION = 8;
  public int JJTLIST = 9;
  public int JJTITEM = 10;
  public int JJTPARAGRAPH = 11;
  public int JJTLINEBREAK = 12;
  public int JJTTEXT = 13;
  public int JJTCHARREF = 14;
  public int JJTCODESPAN = 15;
  public int JJTEMPHASIS = 16;
  public int JJTCOMMENT = 17;
  public int JJTINLINEURL = 18;
  public int JJTLINK = 19;
  public int JJTIMAGE = 20;
  public int JJTTAG = 21;
  public int JJTTAGATTRIBUTELIST = 22;
  public int JJTTAGBODY = 23;
  public int JJTTAGATTRIBUTE = 24;
  public int JJTEMPTYTAG = 25;
  public int JJTSTARTTAG = 26;
  public int JJTENDTAG = 27;


  public String[] jjtNodeName = {
    "Document",
    "void",
    "Header",
    "Ruler",
    "Quote",
    "Line",
    "Code",
    "CodeText",
    "ResourceDefinition",
    "List",
    "Item",
    "Paragraph",
    "LineBreak",
    "Text",
    "CharRef",
    "CodeSpan",
    "Emphasis",
    "Comment",
    "InlineUrl",
    "Link",
    "Image",
    "Tag",
    "TagAttributeList",
    "TagBody",
    "TagAttribute",
    "EmptyTag",
    "StartTag",
    "EndTag",
  };
}
/* JavaCC - OriginalChecksum=47f5ea0baa472de3ba02c118aabf9f88 (do not edit this line) */
